### ISSUE TITLE
No GPU acceleration

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-up-board#26]
The latest `2.2.0+rev1` does not seem to have GPU acceleration. As tested by @curcuz, every GPU flag is disabled and no HW acceleration is detected by chromium.

**Comment by imrehg** [comment]
Sorry, should be filed at https://github.com/resin-os/resinos/issues/370 I guess...

**Comment by imrehg** [comment]
Refiled here as requested.

**Comment by curcuz** [comment]
from the investigation @telphan performed, it turns out the issue is with the mesa libraries that are installed by `debian:jessie`. The way to fix this is to update these packages.
To do that add the jessie-backports mirror to your source.list file, by adding the following line to your Dockerfile:
`RUN echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list`
Lastly use apt-get with `-t jessie-backports` flag to install from that source:
`apt-get -t jessie-backports install {packages}`

**Comment by floion** [comment]
@curcuz maybe we can have this directly in the base images?

**Comment by floion** [comment]
cc @nghiant2710 ^

**Comment by floion** [comment]
@telphan can this be closed now? What is the current resolution?

**Comment by nghiant2710** [comment]
@curcuz @telphan can you please test this again using `debian:stretch` as the base images which has a newer stable mesa library

**Comment by floion** [comment]
ping @telphan ^

**Comment by floion** [comment]
ping @telphan

**Comment by telphan** [comment]
@nghiant2710 will do

**Comment by floion** [comment]
ping @telphan

**Comment by floion** [comment]
ping @telphan

**Comment by floion** [comment]
ping @telphan

**Comment by telphan** [comment]
@nghiant2710 yes, `debian:stretch` should do the trick here.

EDIT: also tested

**Comment by floion** [comment]
So @telphan can this be closed? Did you test it with debian:stretch and confirm the issue is no longer present?

**Comment by telphan** [comment]
This was tested on debian:stretch. Closing the ticket as this is fixed.
